### ISSUE TITLE
Draw wave chart and spectrum map 绘制波形图和频谱图

### ISSUE THREAD

**Issue by lb-chc** [hww/varp_oscilloscope_doc#1]
Hi,I have a wave of waveforms that have been generated.
Want to view its waveform map and spectrum in Unity
Because I don't have an oscilloscope experience
So I don't know how to set it......
Or do I need some modifications to implement this feature?

I hope to get this chart:
![pyroshock-time-spectrum](https://user-images.githubusercontent.com/69136546/121367585-00626a00-c96d-11eb-8199-82d4e33039b5.jpeg)

你好,我有一段生成完毕的波形样本,想在unity中查看它的波形图和频谱图,因为我没有示波器的使用经验,所以我不知道该怎么设置它......或者我需要一些修改来实现这个功能?

我希望得到这样的图表:

**Comment by hww** [comment]
My project focused on registering the game's values to a buffer and display it as the waveform. The functionality does not have the import and export features. So you can't do what you need unless you will implement additional functionality. 

In case if you need to draw existing (previously sampled data), you can do it without my project. Just make your own code, for it. Draw your waveforms on the RenderTexture and apply this texture to a plane.

https://docs.unity3d.com/Manual/class-RenderTexture.html
https://docs.unity3d.com/ScriptReference/RenderTexture.html

From my code, all what you need to learn - this file https://github.com/hww/varp_oscilloscope/blob/master/Src/OscRenderer.cs

But you have to make your solution :)
